jobs:
  run-test:
    name: Publish
    runs-on:
      - ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Create index files
        run: |
          python indexer.py
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y cargo
          cargo install mdbook
          export PATH=$PATH:$HOME/.cargo/bin
          mdbook build
      - name: Publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 cp book s3://carnet.danielhan.dev/ --recursive
name: Publisher
on:
  push:
    branches:
      - master
